#!/bin/bash
set -e
currentVersion=$(npm pkg get version | sed 's/"//g')
npm run build
echo bundled UI
npm run package
echo packaged application
scp "./dist/admin-console_${currentVersion}_arm64.deb" "austin@console:./Desktop/admin-console_${currentVersion}_arm64.deb"
echo transfered package to target
ssh austin@raspberrypi "sudo apt install ./Desktop/admin-console_${currentVersion}_arm64.deb"
echo install complete, rebooting target
ssh austin@console "sudo reboot now"
